// Verilog netlist generated by RFSiP netlister
// Cadence Design Systems, Inc.

module myInverter (
\input! ,\output  );
input  \input! ;
output  \output ;
wire \vdd! ;
wire \vss! ;
wire \output ;
wire \input! ;

PMOS_VTL    
 M0  ( .S( \vdd!  ), .G( \input!  ), .B( \vdd!  ),
 .D( \output  ) );

NMOS_VTL    
 M1  ( .S( \vss!  ), .G( \input!  ), .B( \vss!  ),
 .D( \output  ) );

endmodule

